baseurl         = "/"
theme           = "casper-two"
languageCode    = "en-US"
disqusShortname = ""
paginate        = 6
#SectionPagesMenu = "main"
publishDir = "docs"

[params]
  title       = "Jahnel Group Blog about ServiceNow"
  subtitle    = "Jahnel Group Blog about ServiceNow"

  cover       = "images/main-background.jpg"
  description = "Blog of few individuals passionate about ServiceNow"
  metaDescription = ""
  googleAnalytics = "UA-91305857-2"
  customCSS = []
  RSSLink = ""

  twitterName = "jahnelgroup"
  fbName = "jahnelgroup"
  githubName = "jahnelgroup"

  logo = "images/jg_logo_white.png"
  orgName = "JahnelGroup"
  orgWebsite = "http://jahnelgroup.com"
  orgDescription = "The most amazing software consulting company ever!"


  author = "EM"
  authorAvatar = "defimg/user-icon.svg"
  authorLocation = "Bandung, ID"
  authorWebsite = "https://eueung.github.io"
  authorDescription = "Describe yourself.."

  pageNotFoundTitle = "404 - Page not found"

  #casper or caspertwo
  singleViewStyle = "caspers"

[taxonomies]
  tag = "tags"
  category = "categories"
  authorNick = "authors"

[permalinks]
  post = "/:slug/"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 200
  target = ""

[[menu.main]]
  name = "Our Site"
  url = "http://servicenow.jahnelgroup.com/"
  weight = 150
  target = "_blank"

[[menu.main]]
  name = "Categories"
  url = "/categories"
  weight = 100
  target = ""

[[params.authors]]
    nick = "jsynowiec"
    name = "Jakub Synowiec"
    github = "shnek"
    location = "Schenectady, NY"
    image = "/images/jsynowiec.jpg"
    background = "/images/shnek-background.jpg"
[[params.authors]]
    nick = "dmann"
    name = "Dylan Mann"
    location = "Schenectady, NY"
    image = "/images/dmann.jpg"

